name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ jmcc-cloud-resume-challenge }}
          AWS_ACCESS_KEY_ID: ${{ AKIAVILGYHVHA5RB73JS }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'CloudResumeChallengeFolder'